prepare_projects: only init subrepos, if no specific project is provided
The fix in f2142f82b ("prepare_projects: only checkout real subrepos")
was not enough: If a repo subdir in a project configuration contains a
non-gitmodules managed repository, prepare_project will errorneously
detect it as a subrepo and try to check it out.

This patch prevents this behaviour. Only update submodules, if no
specific project name is provided.

Signed-off-by: Ralf Ramsauer <ralf.ramsauer@oth-regensburg.de>

diff --git a/prepare_projects b/prepare_projects
--- a/prepare_projects
+++ b/prepare_projects
@@ -17,22 +17,15 @@ function die {
 
 if [ -z "$1" ]
 then
-	projects=$(find -mindepth 1 -maxdepth 1 -type d)
+	projects=("busybox" "PreemptRT")
+	git submodule update --init || die "Submodule init failed"
 else
 	projects=$1
 fi
 
-for project in $projects
+for project in "${projects[@]}"
 do
-	cd $project
-	# check if repository is a subrepo
-	git -C repo rev-parse 2>/dev/null
-	if [ $? == "0" ]
-	then
-		echo "Subrepo found. Updating Subrepo."
-		git submodule update --init repo || \
-			die "submodule update failed"
-	fi
+	cd $project 2>/dev/null || die "Unknown project: $project"
 	prepare_project ${project}.cfg || \
 		die "prepare_project failed for: $project"
 	cd ..
